services:
  broker:
    image: eclipse-mosquitto:2.0
    container_name: broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped #Restart the broker unless stopped manually

  broadcaster:
    build:
      context: ./services/broadcaster
    environment:
      MQTT_HOST: ${MQTT_HOST:-broker}
      MQTT_PORT: ${MQTT_PORT:-1883}
      BROADCAST_TOPIC_PREFIX: ${BROADCAST_TOPIC_PREFIX:-sandbox}
      BROADCAST_INTERVAL: ${BROADCAST_INTERVAL:-5}
      MQTT_QOS: ${MQTT_QOS:-1}
    depends_on:
      - broker
    restart: unless-stopped

  consumer:
    build:
      context: ./services/consumer
    environment:
      MQTT_HOST: ${MQTT_HOST:-broker}
      MQTT_PORT: ${MQTT_PORT:-1883}
      BROADCAST_TOPIC_PREFIX: ${BROADCAST_TOPIC_PREFIX:-sandbox}
      FORWARD_TOPIC: ${FORWARD_TOPIC:-sandbox/processed}
      MQTT_QOS: ${MQTT_QOS:-1}
      TRANSFORMER_URL: ${TRANSFORMER_URL:-http://transformer:8000/transform}
      TRANSFORMER_TIMEOUT: ${TRANSFORMER_TIMEOUT:-5}
    depends_on:
      broker:
        condition: service_started
      transformer:
        condition: service_started
    restart: unless-stopped

  transformer:
    build:
      context: ./services/transformer
    ports:
      - "8000:8000"
    restart: unless-stopped
