services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  publisher:
    build:
      context: ./services/publisher
    environment:
      MQTT_HOST: broker
      MQTT_PORT: "1883"
      MQTT_TOPIC: sandbox/events
      PUBLISH_INTERVAL_SECONDS: "5"
      MQTT_QOS: "1"
    depends_on:
      - broker
    restart: unless-stopped

  consumer:
    build:
      context: ./services/consumer
    environment:
      MQTT_HOST: broker
      MQTT_PORT: "1883"
      MQTT_TOPIC: sandbox/events
      MQTT_QOS: "1"
    depends_on:
      - broker
    restart: unless-stopped
